 Implement the K-nearest neighbors (KNN) algorithm from scratch. Given a
 dataset and a query point, classify the query based on the majority label of its k-nearest
 neighbors

In [1]:
import numpy as np
from collections import Counter

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

def knn_classify(X_train, y_train, query_point, k=3):
    distances = []
    for i, data_point in enumerate(X_train):
        dist = euclidean_distance(data_point, query_point)
        distances.append((dist, y_train[i]))

    distances = sorted(distances, key=lambda x: x[0])[:k]
    k_nearest_labels = [label for _, label in distances]
    majority_label = Counter(k_nearest_labels).most_common(1)[0][0]
    
    return majority_label

if __name__ == "__main__":
    X_train = np.array([[1, 2], [2, 3], [3, 4], [6, 7], [7, 8], [8, 9]])
    y_train = np.array([0, 0, 0, 1, 1, 1])
    query_point = np.array([5, 5])
    k = 3
    predicted_label = knn_classify(X_train, y_train, query_point, k)
    
    print(f"Predicted label for query point {query_point} is: {predicted_label}")


Predicted label for query point [5 5] is: 0


 Implement logistic regression in Python. Include training using gradient descent,
 and calculate class probabilities for binary classification.

In [2]:
import numpy as np

class LogisticRegression:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.learning_rate = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self.sigmoid(linear_model)

            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X, threshold=0.5):
        y_predicted_proba = self.predict_proba(X)
        return [1 if i >= threshold else 0 for i in y_predicted_proba]

# Example usage
if __name__ == "__main__":
    from sklearn.model_selection import train_test_split
    from sklearn import datasets
    from sklearn.preprocessing import StandardScaler

    bc = datasets.load_breast_cancer()
    X, y = bc.data, bc.target

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    model = LogisticRegression(learning_rate=0.01, n_iters=1000)
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = np.sum(predictions == y_test) / len(y_test)
    print(f"Accuracy: {accuracy}")


Accuracy: 0.9824561403508771


Write a function to perform matrix multiplication without using external libraries
 like NumPy. Multiply two matrices representing weight matrices and input vectors in a neural
 network layer.

In [3]:
def matrix_multiply(A, B):
    # Get the dimensions of the matrices
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Number of columns in A must be equal to number of rows in B.")

    # Initialize result matrix C with zeros
    C = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform matrix multiplication
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]

    return C

# Example usage
if __name__ == "__main__":
    # Example matrices (weights and input)
    A = [[1, 2, 3],
         [4, 5, 6]]
    
    B = [[7, 8],
         [9, 10],
         [11, 12]]

    result = matrix_multiply(A, B)
    for row in result:
        print(row)


[58, 64]
[139, 154]


 Write a Python function that deep copies a neural network represented as a
 nested list of layers, where each layer contains weight matrices

In [4]:
def deep_copy_network(network):
    if isinstance(network, list):
        return [deep_copy_network(layer) for layer in network]
    else:
        return network

if __name__ == "__main__":
    
    original_network = [
        [[0.2, 0.8], [0.5, 0.1]],  
        [[0.6, 0.4, 0.9], [0.3, 0.7, 0.2]]  
    ]
    
    copied_network = deep_copy_network(original_network)
    copied_network[0][0][0] = 99

    print("Original network:")
    print(original_network)
    print("\nCopied network:")
    print(copied_network)


Original network:
[[[0.2, 0.8], [0.5, 0.1]], [[0.6, 0.4, 0.9], [0.3, 0.7, 0.2]]]

Copied network:
[[[99, 0.8], [0.5, 0.1]], [[0.6, 0.4, 0.9], [0.3, 0.7, 0.2]]]


Implement a moving average filter for a time series. Given a series of numbers
 and a window size, return the moving average of the series

In [5]:
def moving_average(series, window_size):
    if window_size <= 0:
        raise ValueError("Window size must be positive")
    
    moving_averages = []
    for i in range(len(series) - window_size + 1):
        window = series[i:i + window_size]
        window_avg = sum(window) / window_size
        moving_averages.append(window_avg)
    
    return moving_averages

# Example usage
if __name__ == "__main__":
    series = [10, 20, 30, 40, 50, 60, 70]
    window_size = 3
    result = moving_average(series, window_size)
    print("Moving averages:", result)


Moving averages: [20.0, 30.0, 40.0, 50.0, 60.0]


: Write a Python function that applies the ReLU activation function to a list of
 inputs

In [6]:
def relu(inputs):
    return [max(0, x) for x in inputs]

# Example usage
if __name__ == "__main__":
    inputs = [-3, -1, 0, 2, 5, -7]
    result = relu(inputs)
    print("ReLU applied to inputs:", result)


ReLU applied to inputs: [0, 0, 0, 2, 5, 0]


 Implement gradient descent to train a linear regression model. Minimize the
 mean squared error by adjusting the model weights iteratively.

In [7]:
import numpy as np

class LinearRegressionGD:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.learning_rate = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            y_predicted = np.dot(X, self.weights) + self.bias
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        return np.dot(X, self.weights) + self.bias


if __name__ == "__main__":
    from sklearn.model_selection import train_test_split
    from sklearn.datasets import make_regression
    X, y = make_regression(n_samples=100, n_features=1, noise=20, random_state=42)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    regressor = LinearRegressionGD(learning_rate=0.01, n_iters=1000)
    regressor.fit(X_train, y_train)
    y_pred = regressor.predict(X_test)
    mse = np.mean((y_test - y_pred) ** 2)
    print(f"Mean Squared Error: {mse}")
    print(f"Model weights: {regressor.weights}")
    print(f"Model bias: {regressor.bias}")


Mean Squared Error: 417.00933221477027
Model weights: [46.73020522]
Model bias: 0.18967596020864966


Write a Python function to perform one-hot encoding of categorical labels for a
 machine learning task.

In [8]:
def one_hot_encode(labels):
    # Get the unique classes in the labels
    unique_labels = list(set(labels))
    
    # Create a dictionary mapping each label to an index
    label_to_index = {label: index for index, label in enumerate(unique_labels)}
    
    # Create the one-hot encoded matrix
    one_hot_encoded = []
    for label in labels:
        one_hot_vector = [0] * len(unique_labels)
        one_hot_vector[label_to_index[label]] = 1
        one_hot_encoded.append(one_hot_vector)
    
    return one_hot_encoded, label_to_index

# Example usage
if __name__ == "__main__":
    labels = ['cat', 'dog', 'bird', 'cat', 'dog', 'bird', 'cat']
    one_hot_matrix, label_mapping = one_hot_encode(labels)
    
    print("One-hot encoded matrix:")
    for row in one_hot_matrix:
        print(row)
    
    print("\nLabel mapping:")
    print(label_mapping)


One-hot encoded matrix:
[0, 0, 1]
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]

Label mapping:
{'dog': 0, 'bird': 1, 'cat': 2}


 Implement a Python function to calculate the cosine similarity between two
 vectors, which is often used in text similarity tasks.

In [9]:
import math

def cosine_similarity(vec1, vec2):
    if len(vec1) != len(vec2):
        raise ValueError("Vectors must be of the same length")
    
    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    magnitude_vec1 = math.sqrt(sum(a**2 for a in vec1))
    magnitude_vec2 = math.sqrt(sum(b**2 for b in vec2))
    
    if magnitude_vec1 == 0 or magnitude_vec2 == 0:
        raise ValueError("One of the vectors has zero magnitude")
    
    return dot_product / (magnitude_vec1 * magnitude_vec2)

if __name__ == "__main__":
    vec1 = [1, 2, 3]
    vec2 = [4, 5, 6]
    similarity = cosine_similarity(vec1, vec2)
    print(f"Cosine similarity: {similarity:.4f}")


Cosine similarity: 0.9746


Given a trained neural network in Python, write a function to prune the network
 by removing neurons that have small or zero weights.

In [10]:
import numpy as np

def prune_neural_network(weights, threshold=1e-5):
    pruned_weights = []
    
    for layer in weights:
        pruned_layer = []
        for neuron_weights in layer:
            if np.linalg.norm(neuron_weights) > threshold:
                pruned_layer.append(neuron_weights)
        pruned_weights.append(pruned_layer)
    
    return pruned_weights

if __name__ == "__main__":
    # Example weights for a simple neural network
    weights = [
        [np.array([0.1, 0.0, 0.3]), np.array([0.0, 0.0, 0.0]), np.array([0.5, 0.7, 0.0])],
        [np.array([0.0, 0.0]), np.array([0.2, 0.1])]
    ]
    
    pruned = prune_neural_network(weights, threshold=1e-5)
    print("Pruned weights:")
    for layer in pruned:
        print(layer)


Pruned weights:
[array([0.1, 0. , 0.3]), array([0.5, 0.7, 0. ])]
[array([0.2, 0.1])]


Implement a Python function to compute the confusion matrix given true and
 predicted labels for a classification task.

In [11]:
import numpy as np

def confusion_matrix(y_true, y_pred):
    unique_labels = np.unique(np.concatenate((y_true, y_pred)))
    matrix = np.zeros((len(unique_labels), len(unique_labels)), dtype=int)

    for true, pred in zip(y_true, y_pred):
        matrix[true][pred] += 1

    return matrix

if __name__ == "__main__":
    y_true = np.array([0, 1, 2, 2, 0, 1, 0])
    y_pred = np.array([0, 0, 2, 2, 0, 1, 1])
    
    cm = confusion_matrix(y_true, y_pred)
    print("Confusion Matrix:")
    print(cm)


Confusion Matrix:
[[2 1 0]
 [1 1 0]
 [0 0 2]]


 Write a Python function that performs mini-batch gradient descent for optimizing
 the weights of a neural network.

In [12]:
import numpy as np

def mini_batch_gradient_descent(X, y, weights, learning_rate=0.01, batch_size=32, epochs=100):
    num_samples = X.shape[0]
    
    for epoch in range(epochs):
        indices = np.arange(num_samples)
        np.random.shuffle(indices)
        X_shuffled = X[indices]
        y_shuffled = y[indices]

        for start in range(0, num_samples, batch_size):
            end = start + batch_size
            X_batch = X_shuffled[start:end]
            y_batch = y_shuffled[start:end]

            predictions = np.dot(X_batch, weights)
            errors = predictions - y_batch
            gradient = np.dot(X_batch.T, errors) / X_batch.shape[0]
            weights -= learning_rate * gradient

    return weights

if __name__ == "__main__":
    # Example data
    X = np.random.rand(100, 10)
    y = np.random.rand(100)
    initial_weights = np.random.rand(10)

    optimized_weights = mini_batch_gradient_descent(X, y, initial_weights, learning_rate=0.01, batch_size=16, epochs=50)
    print("Optimized weights:")
    print(optimized_weights)


Optimized weights:
[-0.02950649  0.45059196 -0.04269402 -0.02379824 -0.10494612  0.59043156
 -0.09994939  0.22188668 -0.05927275  0.06480126]


Implement k-means clustering from scratch. Given a dataset and the number of
 clusters 
k , return the cluster assignments for each data point.

In [13]:
import numpy as np

def kmeans(X, k, max_iters=100):
    num_samples, num_features = X.shape
    # Randomly initialize the centroids
    centroids = X[np.random.choice(num_samples, k, replace=False)]
    cluster_assignments = np.zeros(num_samples)

    for _ in range(max_iters):
        # Assign clusters
        for i in range(num_samples):
            distances = np.linalg.norm(X[i] - centroids, axis=1)
            cluster_assignments[i] = np.argmin(distances)

        # Update centroids
        new_centroids = np.array([X[cluster_assignments == j].mean(axis=0) for j in range(k)])
        
        if np.all(centroids == new_centroids):
            break
        
        centroids = new_centroids

    return cluster_assignments

if __name__ == "__main__":
    # Example data
    X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
    k = 2
    
    assignments = kmeans(X, k)
    print("Cluster assignments:")
    print(assignments)


Cluster assignments:
[0. 0. 0. 1. 1. 1.]


 Implement a Python function to calculate the softmax of a list of numbers, which
 is used in multi-class classification problems

In [14]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum(axis=0)

if __name__ == "__main__":
    scores = [2.0, 1.0, 0.1]
    probabilities = softmax(scores)
    print("Softmax probabilities:")
    print(probabilities)


Softmax probabilities:
[0.65900114 0.24243297 0.09856589]


Write a Python function to compute the TF-IDF (Term Frequency-Inverse
 Document Frequency) for a list of documents.


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

def compute_tfidf(documents):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(documents)
    return tfidf_matrix, vectorizer.get_feature_names_out()

if __name__ == "__main__":
    documents = [
        "the cat in the hat",
        "the cat sat on the mat",
        "the dog in the fog"
    ]
    
    tfidf_matrix, feature_names = compute_tfidf(documents)
    print("TF-IDF Matrix:")
    print(tfidf_matrix.toarray())
    print("Feature Names:")
    print(feature_names)


TF-IDF Matrix:
[[0.40352536 0.         0.         0.53058735 0.40352536 0.
  0.         0.         0.62674687]
 [0.34101521 0.         0.         0.         0.         0.44839402
  0.44839402 0.44839402 0.52965746]
 [0.         0.50165133 0.50165133 0.         0.38151877 0.
  0.         0.         0.59256672]]
Feature Names:
['cat' 'dog' 'fog' 'hat' 'in' 'mat' 'on' 'sat' 'the']


Implement an algorithm to find the principal components of a dataset using
 singular value decomposition (SVD), which is a core part of PCA (Principal Component
 Analysis)

In [17]:
import numpy as np

def pca_svd(X, n_components):
    X_meaned = X - np.mean(X, axis=0)
    U, S, Vt = np.linalg.svd(X_meaned, full_matrices=False)
    principal_components = Vt[:n_components]
    return principal_components

if __name__ == "__main__":
    # Example dataset
    X = np.array([[2.5, 2.4],
                  [0.5, 0.7],
                  [2.2, 2.9],
                  [1.9, 2.2],
                  [3.1, 3.0],
                  [2.3, 2.7],
                  [2, 1.6],
                  [1, 1.1],
                  [1.5, 1.6],
                  [1.1, 0.9]])
    
    n_components = 1
    principal_components = pca_svd(X, n_components)
    print("Principal Components:")
    print(principal_components)


Principal Components:
[[-0.6778734  -0.73517866]]


 Write a Python function to calculate the AUC-ROC score for a binary
 classification problem, given the true labels and predicted probabilities.

In [18]:
from sklearn.metrics import roc_auc_score

def calculate_auc_roc(y_true, y_scores):
    return roc_auc_score(y_true, y_scores)

if __name__ == "__main__":
    # Example true labels and predicted probabilities
    y_true = [0, 1, 1, 0, 1]
    y_scores = [0.1, 0.4, 0.35, 0.8, 0.7]
    
    auc_roc = calculate_auc_roc(y_true, y_scores)
    print("AUC-ROC score:", auc_roc)


AUC-ROC score: 0.5


Implement a Python function to apply dropout regularization to the neurons of a
 given neural network during training

In [19]:
import numpy as np

def apply_dropout(layer_output, dropout_rate):
    if dropout_rate < 0 or dropout_rate >= 1:
        raise ValueError("Dropout rate must be between 0 and 1.")
    
    mask = np.random.binomial(1, 1 - dropout_rate, size=layer_output.shape)
    return layer_output * mask / (1 - dropout_rate)

if __name__ == "__main__":
    # Example layer output
    layer_output = np.array([[0.2, 0.8, 0.5],
                             [0.4, 0.9, 0.3],
                             [0.6, 0.2, 0.1]])
    
    dropout_rate = 0.5
    output_with_dropout = apply_dropout(layer_output, dropout_rate)
    print("Layer output after applying dropout:")
    print(output_with_dropout)


Layer output after applying dropout:
[[0.  1.6 0. ]
 [0.8 1.8 0. ]
 [0.  0.  0. ]]


 Write a Python function to perform feature scaling using standardization (z-score
 normalization), which transforms features to have a mean of 0 and a standard deviation of 1.

In [20]:
import numpy as np

def standardize_features(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    standardized_X = (X - mean) / std
    return standardized_X

if __name__ == "__main__":
    # Example dataset
    X = np.array([[1, 2],
                  [2, 3],
                  [3, 4],
                  [4, 5],
                  [5, 6]])
    
    standardized_X = standardize_features(X)
    print("Standardized features:")
    print(standardized_X)


Standardized features:
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


 Implement a Python function to compute the cross-entropy loss for a multi-class
 classification problem, given the true labels and predicted probabilities

In [21]:
import numpy as np

def cross_entropy_loss(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    num_samples = y_true.shape[0]
    loss = -np.sum(y_true * np.log(y_pred + 1e-15)) / num_samples
    return loss

if __name__ == "__main__":
    # Example true labels (one-hot encoded) and predicted probabilities
    y_true = np.array([[1, 0, 0],
                       [0, 1, 0],
                       [0, 0, 1]])
    y_pred = np.array([[0.7, 0.2, 0.1],
                       [0.1, 0.8, 0.1],
                       [0.2, 0.2, 0.6]])
    
    loss = cross_entropy_loss(y_true, y_pred)
    print("Cross-entropy loss:", loss)


Cross-entropy loss: 0.3635480396729762
